name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.5
        with:
          start: npm run cy:run
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 300
      - name: Cypress Generate Report
        run: npm run cy:report
        env:
          RECIPEINTS_LIST: ${{ secrets.RECIPEINTS_LIST }}
      # - name: Deploy HTML Results
        # uses: JamesIves/github-pages-deploy-action@3.8.0
        # with:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   BRANCH: gh-pages
        #   FOLDER: mochawesome-report
        #   REPOSITORY: bujupah/cy-test
