name: Cypress Tests
on:
  push:
    branches:
      - master
  schedule: 
    - cron: '0 12 * * *'
jobs:
  cypress-generate-report:
    runs-on: ubuntu-latest
    name: Generate Cypress Report
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5.0.5

      # Generate a report from the test results
      - name: Cypress Generate Report
        run: npm run cy:report

      # Save test results to a directory so we can upload them as an artifact
      - name: Save mochawesome-report in test-results
        run: mv mochawesome-report test-results
        
      - name: Save mochawesome
        run: mv mochawesome.json test-results/data.json
      
      # Upload test results to GitHub as artifacts
      - name: Archive Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/
      
      # Upload test videos to GitHub as artifacts
      - name: Archive Test Videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos/

      # Upload test screenshots to GitHub as artifacts
      - name: Archive Test Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots/
  
  cypress-publish-report:  
    runs-on: ubuntu-latest
    name: Deploy on Github Pages
    needs: cypress-generate-report
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Download Test Results
      uses: actions/download-artifact@v3
      with:
        name: test-results

    - name: Prepare website
      run: mv mochawesome.html index.html

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: .

  cypress-share-report:  
    runs-on: ubuntu-latest
    name: Sharing via Email
    needs: cypress-generate-report
    steps:
      - name: Download Test Results
        uses: actions/download-artifact@v3
        with:
          name: test-results
      
      - name: Rename mochawesome.html to index.html
        run: mv mochawesome.html index.html

      - name: Listing folder
        run: ls -la

      - name: Send mailer
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: 587
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        uses: devellany/send-mail@v1.0.2
        with:
          host: $SMTP_SERVER
          port: 587
          account: $SMTP_USERNAME
          password: $SMTP_PASSWORD
          sender: 'Cypress Test'
          from: $SMTP_USERNAME
          to: $EMAIL_RECIPIENT
          subject: 'Cypress Test Report'
          body: 'Please view the attached report.'
          attachments: '[{"path": "result.zip"}]'