name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.5
      - name: List files
        run: ls results -la
      - name: Cypress Generate Report
        run: npm run cy:report
      - name: Save Test Results
        run: mv cypress/reports/mochawesome-report cypress/reports/test-results
      - name: Archive Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: results
  
  cypress-report:  
    runs-on: ubuntu-latest
    name: Deploy HTML Results
    needs: cypress-run
    steps:
    - name: List files
      run: ls -la
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Download Test Results
      uses: actions/download-artifact@v2
      with:
        name: results
    - name: List files
      run: ls -la
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.4.1
      with:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: results